### ISSUE TITLE
Example runs fine but own data will not

### ISSUE THREAD

**Issue by jnederend** [atenah/Plot-Boundary-Extraction-CSV-KML#9]
After figuring out where the bug was in the csv2kml.py and fixing it (was in the latest pull request), the example dataset runs perfectly. When I try to run my own trial, I get the following error:
```
Traceback (most recent call last):
  File "csv2kml.py", line 203, in <module>
    inputFile = InputFile(conf.input_filename)
  File "C:\Plot_extractor\lib\csvfile.py", line 13, in __init__
    self.rownums.add(int(row[0]))
ValueError: invalid literal for int() with base 10: ''
```

I've set my CSV files (and manually edited the XML because documentation does not make its purpose clear + it does not automatically update after I alter the config CSV) exactly as in the example dataset. The only difference is that use opposite corners, with plot 1 in the bottom left, and the last one in the top right. I do not have any gaps between columns so I put the gap as 0.0 m and its occurrence between columns 2 and 3.

**Comment by jnederend** [comment]
I've re-visited this tool and can run it on my own map. The problem is that no matter what points I choose, or how I set up the sample_input.csv, the tool decides to begin ordering the plots in the wrong direction. 

I set up my points 1 at the opposite corners compared to the example (i.e. mine are at bottom left and top right) because they are ordered sequentially from left to right if one were facing the start of plot 101. 
`row, col, plot`
`1,1,101`
`1,2,102`
`...`

However, I did try with the other coordiantes and still did not have any luck. The KML is always crooked, and the plot sizes are far from those that I provided. I needs to be rotated in  a clockwise direction. 
![image](https://user-images.githubusercontent.com/16839764/39639366-0f34eba0-4f97-11e8-9c4e-3ab0462b30fa.png)
